name: make

on:
  workflow_dispatch:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build_ubuntu-amd64_latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: prerequisites
    # pre-installed on ubuntu-1804: build-essential, git 2.28.0, cmake 3.10/3.17, make
    # pre-installed: clang 6.0 / 8 / 9, gcc/++ 7.5.0/8.4.0/9.3.0
      run: |
        sudo apt -qq update
        sudo apt -yqq install libusb-1.0-0-dev \
        libfftw3-dev libcurl4-gnutls-dev help2man ntp libsndfile-dev # libliquid-dsp
    - name: make
      run: |
        make
    - name: compress
      run: |
        tar zcvf ft8mon_build_ubuntu-amd64_latest.tar.gz \
        --exclude=Makefile \
        .
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v5
      with:
        name: ubuntu_latest_build.tar.gz
        path: ft8mon_build_ubuntu-amd64_latest.tar.gz

  build_macos_latest:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - name: prerequisites
    # pre-installed on macos-10.15: git 2.28.0, cmake 3.18.2, libusb 1.0.23
    # pre-installed: clang/LLVM 10.0.1, gcc/++ 8.4.0/9.3.0 libcurl
      run: |
        brew install libusb help2man ntp libsndfile fftw liquid-dsp
    - name: make
      run: make
    - name: compress
      run: |
        tar zcvf ft8mon_build_macos-latest.tar.gz \
        --exclude=Makefile \
        .
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v5
      with:
        name: macos_latest_build.tar.gz
        path: ft8mon_build_macos-latest.tar.gz
